openapi: 3.0.0
info:
  title: Chainlabs Full Clusters API
  description: "### \n\nThe Chainlabs Full Clusters API allows clients to programmatically retrieve attribution labels for wallet addresses"
  version: 0.1.0
servers:
- url: /
paths:
  /labels:
    post:
      tags:
        - Labels
      summary: Get label for wallet address
      description: |-
        Returns label for the provided blockchain wallet addresses(upto 50 addresses in each request).
        
        Unlabeled addresses are returned without attribution data.
        
        Out of scope entities include category level labels only, with no entity-level details.
      operationId: label
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelsRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelsResponse'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    LabelsRequest:
      type: object
      required:
        - addresses
      properties:
        addresses:
          description: List of blockchain wallet addresses (maximum 50).
          type: array
          minItems: 1
          maxItems: 50
          items:
            type: string
          example:
            - 34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
            - 1DcT5Wij5tfb3oVViF8mA8p4WrG98ahZPT
    LabelsResponse:
      type: object
      properties:
        results:
          description: Array of attribution results for the queried addresses.
          type: array
          items:
            type: object
            properties:
              address:
                description: Blockchain wallet address that was queried.
                type: string
                example: 34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
              token:
                $ref: '#/components/schemas/TokenEnum'
              entityId:
                description: Unique integer assigned to the attributed entity.
                type: integer
                format: int64
                example: 10
              entityName:
                description: Official or recognized name of the attributed entity.
                type: string
                example: Binance
              categoryId:
                description: Unique ID assigned to the category.
                type: string
                example: CEFI
              category:
                description: Category of the entity.
                type: string
                example: Centralized Finance
              confidence_level:
                type: string
                description: Indicates the confidence level of the assigned label.
                enum:
                  - high
                  - mid
                  - low
          example:
            - address: 34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
              token: BTC
              entityId: 10
              entityName: Binance
              categoryId: CEFI
              category: Centralized Finance
              confidence_level: high
            - address: 1DcT5Wij5tfb3oVViF8mA8p4WrG98ahZPT
              token: BTC
              entityId: NULL
              entityName: NULL
              categoryId: CEFI
              category: Centralized Finance
              confidence_level: low
    TokenEnum:
      type: string
      description: "A specific cryptocurrency or token associated with the wallet address."
      oneOf:
      - title: BTC
      - title: TRX
      - title: ETH
